llama8: 
  path: /scratch/prj/charnu/seacow_hf_cache/models--meta-llama--Meta-Llama-3.1-8B-Instruct/snapshots/0e9e39f249a16976918f6564b8830bc894c89659
  template: llama3

qwen7:
  path: /scratch/prj/charnu/seacow_hf_cache/models--Qwen--Qwen2.5-7B-Instruct/snapshots/a09a35458c702b33eeacc393d103063234e8bc28
  template: qwen

qwen14:
  path: /scratch/prj/charnu/seacow_hf_cache/models--Qwen--Qwen2.5-14B-Instruct/snapshots/cf98f3b3bbb457ad9e2bb7baf9a0125b6b88caa8
  template: qwen

qwen32:
  path: /scratch/prj/charnu/seacow_hf_cache/models--Qwen--Qwen2.5-32B-Instruct/snapshots/5ede1c97bbab6ce5cda5812749b4c0bdf79b18dd
  template: qwen
